### ISSUE TITLE
Key don't force UPPERCASE

### ISSUE THREAD

**Issue by 54mu3l** [thibault-vanderseypen/vsce-i18n-json-editor#1]
Hi,

Amazing extension! It's really helpful.

The only annoying thing is that the keys always (automatically) change to UPPERCASE.
But our keys are camelCase..

It would be really great if someone could disable this rule. Because otherwise it gets really hard to add new keys or edit existing keys.

Currently I edit all json-files by hand (for key-changes)...

Would be great
Cheers!

**Comment by thibault-vanderseypen** [comment]
Hello,

Thank you for your message, It's very nice of you !

I already adapted the code and published it on the marketplace (v1.1.2)
You can now disable the uppercase with the "i18nJsonEditor.forceKeyUPPERCASE" property". 
![i18n-forcekeyuppercase](https://user-images.githubusercontent.com/70330053/97633516-82cc9800-1a34-11eb-8107-2509299d9e98.png)

All the best,
Thibault
