### ISSUE TITLE
How to add folders for each languages 

### ISSUE THREAD

**Issue by indramal** [thibault-vanderseypen/vsce-i18n-json-editor#15]
I have following format folders for each JSONs.

 - locals
 - - en
 - - - translation.json
 - - fr 
 -  - - translation.json

How to add this to get columns for each languages?

**Comment by thibault-vanderseypen** [comment]
Hello,
It's still on my to-do list to have a different structure (see https://github.com/thibault-vanderseypen/vsce-i18n-json-editor/issues/12).

For now, the only working structure is:
```
    - i18n (or whatever)
        - en.json
        - fr.json
        - ...
 ```

A new development will be done soon.

Have a great day!

**Comment by DionJChapman** [comment]
Try this version: https://marketplace.visualstudio.com/items?itemName=NativeBit.i18n-l10n-editor

although it will not add folders, it does read the files in any sub folder

**Comment by DionJChapman** [comment]
> although it will not add folders, it does read the files in any sub folder

The latest version on the plugin above now supports these file structures.

**Comment by DionJChapman** [comment]
@thibault-vanderseypen this can be closed
