### ISSUE TITLE
translator service

### ISSUE THREAD

**Issue by WinnieS0728** [thibault-vanderseypen/vsce-i18n-json-editor#20]
hello, thanks to build this great extension,
i'm using translator service and have some questions,

this is my settings.json in .vscode

``` 
{
... other settings,
"i18nJsonEditor.translationService": "MicrosoftTranslator",
"i18nJsonEditor.translationServiceApiKey": "my api key"
}
 ```

and this is my view in json editor

![my result image](https://github.com/thibault-vanderseypen/vsce-i18n-json-editor/assets/116339731/034421e1-6d18-4cda-80ce-dd6340c15b69)

and my question is 

- how to trigger the translator
- why my UI color is still blue but not green ( i don't know if this matter )

i click the translate button and nothing happened, in my Microsoft page no use history too

i want to know how to fix it , thank you

**Comment by DionJChapman** [comment]
Try this version: https://marketplace.visualstudio.com/items?itemName=NativeBit.i18n-l10n-editor

Microsoft changed how the API worked, and it is no longer compatible with this Extension version.

My version also works with zh-Hans and zh-Hant automatically creating the zh file for compatibility with the flutter gen-l10n

**Comment by WinnieS0728** [comment]
thanks for reply.
but i think i cant use this extension.

this is my .vscode setting (no other setting, just this 2 lines)

```
{
  "i18n-l10n-editor.sortKeyTogether": true,
  "i18n-l10n-editor.supportedFolders": ["locales"]
}
```

and this is my project folders

![image](https://github.com/thibault-vanderseypen/vsce-i18n-json-editor/assets/116339731/a4975876-9968-43fa-b57b-e95cdd4220b6)

i got some questions.

PS. I restart vscode after every change so i think it's not unsaved error.

## button on status bar

when i click i18n / i10n editor button on status bar, nothing show in my edit page.

![image](https://github.com/thibault-vanderseypen/vsce-i18n-json-editor/assets/116339731/fa2fd8c6-1dd0-424f-b036-56db9058e9c2)

Add button is not working too.

## right click on folder

so i try right click on folder way.

now language can detect, but when i click add button, it only add new key, i can't edit my translate.

same error when right click my "page a" and "page b" folder.

show like this

![image](https://github.com/thibault-vanderseypen/vsce-i18n-json-editor/assets/116339731/0ac094e5-f6b0-4933-aa79-e30930e49bb1)

## name space

i want to spread my translations by using deffrent folder.

so i add my .vscode setting, now look like this

```
{
  "i18n-l10n-editor.sortKeyTogether": true,
  "i18n-l10n-editor.supportedFolders": ["locales"],
  "i18n-l10n-editor.workspaceFolders": [
      { "name": "page_A", "path": "./locales/page a" },
      { "name": "page_B", "path": "./locales/page b" },
  ]
}
```

now my edit page can detect folders,

![image](https://github.com/thibault-vanderseypen/vsce-i18n-json-editor/assets/116339731/45bf6de5-a4cc-4f2d-b6d3-4cd8cef03304)

but still cant edit and add button not working.

## type by my own

last thing i tried is type translation in .json by my own.

|  | remove workspaceFolders | with wordspaceFolders defined |
| --- | --- | --- |
| button on status bar | not working |  not working |
| right click on folder | can show existing translation, but function not working |  not working |

this image is remove workspaceFolders setting and right click on folder

![image](https://github.com/thibault-vanderseypen/vsce-i18n-json-editor/assets/116339731/abb94442-db49-47b3-8f13-85971cea1574)

the last last thing and the most important thing is thank you for sharing this new extension, it's look great from readme demo (better UI i think), but i can't use this extension, maybe is my setting error, you can give me any advise any time, thank you !!

**Comment by DionJChapman** [comment]
> when i click i18n / i10n editor button on status bar, nothing show in my edit page.

Could you create a file in your project called l10n.yaml and add the following?

`arb-dir: {path to locales}

template-arb-file: en.json

output-localization-file: app_localizations.dart`

This should fix your issues.

**Comment by WinnieS0728** [comment]
i create I10n.yaml and code like this

```
arb-dir: ./locales

template-arb-file: en.json

output-localization-file: app_localizations.dart
```

now my folder look like this 

![image](https://github.com/thibault-vanderseypen/vsce-i18n-json-editor/assets/116339731/4afbb373-885b-4c03-a808-7df88e6a3f56)

nothing change.
my project is VITE 4.3.9 + react 18.0.37 + typescript 5.0.2
is there any setting i missing ?

**Comment by DionJChapman** [comment]
Hi

Could you please send me your locles directory zipped?

**Comment by WinnieS0728** [comment]
sure ! here is my locales folder

[locales.zip](https://github.com/thibault-vanderseypen/vsce-i18n-json-editor/files/12331473/locales.zip)

**Comment by DionJChapman** [comment]
Hi

It seems it doesn't like files with the same name, if you change it as follows for now i will see if i can fix it soon.
<img width="335" alt="Screenshot 2023-08-14 at 2 36 11 pm" src="https://github.com/thibault-vanderseypen/vsce-i18n-json-editor/assets/123435162/3757e3fe-16c4-457a-933f-2e4016e4f418">

**Comment by WinnieS0728** [comment]
Hi, i changed and still cant use.

but something different is right click on folders,
it detect all file as new language.

![image](https://github.com/thibault-vanderseypen/vsce-i18n-json-editor/assets/116339731/1b19e079-e6f3-4166-90e3-8ae1bcbd9296)

**Comment by DionJChapman** [comment]
Hi

This will take me some time to work out as I have tried it on both Windows 11 and MacOS, with both working as expected.

**Comment by WinnieS0728** [comment]
sure,
thank you for your help

**Comment by DionJChapman** [comment]
> sure, thank you for your help

Thanks for being patient with this.

I looked at your repositories and found one that matched your descriptions. This allowed me to reproduce the problem, and I have now fixed it and a few other issues.

Please download this zip file from my DropBox for testing: https://www.dropbox.com/s/lt30vnhb64saff2/i18n-l10n-editor-3.2.0.vsix.zip?dl=0

Unzip this to your project directory and then right-click it from VSCode and choose 'Install Extensions VSIX"

Also can you please log this issue in my GitHub: https://github.com/DionJChapman/Localization-Internationalization-Editor

**Comment by DionJChapman** [comment]
@thibault-vanderseypen this can be closed
