### ISSUE TITLE
dynamic folder name

### ISSUE THREAD

**Issue by egyleader** [thibault-vanderseypen/vsce-i18n-json-editor#21]
the extension should work on any folder , I should be able to right click on any folder and choose the option "i18n JSON Editor" not only folders named "i18n"

**Comment by DionJChapman** [comment]
> the extension should work on any folder , I should be able to right click on any folder and choose the option "i18n JSON Editor" not only folders named "i18n"

Hi

I have taken over this extension from Thibault, and this request works as you want in that extension. As well as many new features. Please check the link below.

https://marketplace.visualstudio.com/items?itemName=NativeBit.i18n-l10n-editor

**Comment by thibault-vanderseypen** [comment]
Yes, don't hesitate to use the DionJChapman's extension :) 
(Fyi the setting : i18nJsonEditor.supportedFolders could help you)
