### ISSUE TITLE
Encoding issue - UTF-8 with BOM

### ISSUE THREAD

**Issue by JuergenRB** [thibault-vanderseypen/vsce-i18n-json-editor#4]
If the translation files '<lang>.json' are saved in the UTF-8 with Bom, nothing is displayed in the editor.
A note in the VSC outputs would be helpful to find out why nothing is displayed.

**Comment by thibault-vanderseypen** [comment]
Wah ! Thanks for the PR Jurgen ! :) I don't have an access to my compute right now but at the end of this week I'll update the plugin. 
Many thanks !

I'll let you know :)
