### ISSUE TITLE
Ignore dots in keys

### ISSUE THREAD

**Issue by RodionNikolaev** [thibault-vanderseypen/vsce-i18n-json-editor#7]
In some cases, we are using flat keys with a dots. Like a **"Report sent. Thank you."**

The output result (if no ended dot):
 "Report sent": {
    " Thank you": "Report sent. Thank you"
  },

Add "keySeparator"  option like in [i18next documentation](https://www.i18next.com/overview/api) 
_(char to separate keys, or false if no separator is preferred)_

For generation results like this:
 "Report sent. Thank you.":  "Report sent. Thank you."

**Comment by alessiocancian** [comment]
I was having issues with dots separation, so I implemented the `keySeparator` option and sent a pull request (#9)
