### ISSUE TITLE
Feature request: Namespaced and nested json files

### ISSUE THREAD

**Issue by RWOverdijk** [thibault-vanderseypen/vsce-i18n-json-editor#8]
It's not uncommon to have nested/namespaced translation files:

```
i18n
├── en
│   ├── components.json
│   └── screens.json
├── nl
│   ├── components.json
│   └── screens.json
```

It would be nice if those could get picked up the way (for example) [Easy I18n](https://plugins.jetbrains.com/plugin/16316-easy-i18n) does it.

**Comment by marviobezerra** [comment]
We support 4 languages using nested namespaces. Not supporting that, kinda of kill this extension for us. 😔

**Comment by DionJChapman** [comment]
> It's not uncommon to have nested/namespaced translation files:

Doing this took way longer than I thought, but it no handles language folder structures. 

The new extension can be found here https://marketplace.visualstudio.com/items?itemName=NativeBit.i18n-l10n-editor

**Comment by RWOverdijk** [comment]
Wat year is it?

**Comment by DionJChapman** [comment]
> Wat year is it?

2023, yeah I know you put this in 2021. I just took over this about 2 months ago, and I am going through the old bugs/feature requests and seeing if I can fix them.

**Comment by RWOverdijk** [comment]
I don't even remember this ticket haha. I'll close it then, thanks!
